# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         asterisk-perl
version:      1.00
version_from: lib/Asterisk.pm
installdirs:  site
requires:
    Digest::MD5:                   0
    IO::Socket:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
