--- #YAML:1.0
name:               asterisk-perl
version:            1.02
abstract:           Asterisk Perl Interface
author:
    - James Golovich <james@gnuinter.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::MD5:  0
    IO::Socket:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
